### ISSUE TITLE
Has stopped developing?

### ISSUE THREAD

**Issue by ykla** [NextBSD/NextBSD#48]
Has stopped developing?

**Comment by svkamp** [comment]
nothing has been done with NextBSD in 11 months, the players involved seem to have all lost interest in the goals. last update and Latest commit c0c4761  on Jul 24, 2016

**Comment by ykla** [comment]
sad

**Comment by LubosD** [comment]
Hey guys, if you want to see launchd outside of macOS, then your best chance is currently [Darling](https://github.com/darlinghq) on Linux.

We've even taken over (and fixed up) libxpc from NextBSD. We're almost ready to use launchd by default for our containers (should be merged into master in a matter of days/weeks tops).

**Comment by TheDharc** [comment]
And why Linux when Darwin's libc and various kernel APIs is the same from FreeBSD? Porting Darwin applications to or from a BSD is easier. I really don't know why Darling is so focused on Linux. There is no technical reason for that.

**Comment by LubosD** [comment]
@TheDharc

- Compared to Linux, almost nobody uses FreeBSD. That's a fact, not a rant. I ran a popular open source oriented website for quite some time and the amount of BSD visitors was super low (around 1%) and dropping steadily over the last decade.
- I want to run macOS apps on a system I use, why would I work on running them on a system I don't use?
- There is no technical benefit for Darling to use a BSD system really. Not sure why you'd find it any easier.

**Comment by langerma** [comment]
@LubosD : I guess you are not right.

BSD still offers some nice stuff, like clean and well documented userland tools and also a very good documented Kernel.

also the networking features that FreeBSD offers are amazing. and well not to mention pf.

**Comment by LubosD** [comment]
@langerma I was replying to "There is no technical reason for [Darling being so focused on Linux]." I didn't mean to say that BSD doesn't offer compelling features.
I'll edit my comment to clarify that.

**Comment by TheDharc** [comment]
- Compared to Linux, almost nobody uses FreeBSD. That's a fact, not a rant.

Yeah, so I gonna keeping developing Windows and macOS-only softwares, specially because this mentality. Besides, nobody uses Linux on desktop :P

- There is no technical benefit of using a BSD system really. Not sure why you'd find it any easier.

I'll avoid to facepalm. Just go ahead.

**Comment by LubosD** [comment]
"Besides, nobody uses Linux on desktop :P"
Compared to BSD, I'd say there are maybe a hundred times more desktop Linux users than desktop BSD users.

"I'll avoid to facepalm. Just go ahead."

No, humor me and tell me what the technical reasons for Darling to focus on BSD are.

**Comment by adouble42** [comment]
well your reasons were so overtly technical surely someone must appease you with a disproportionate amount of effort beyond an off the cuff dismissal, and accepting your presumptuous and completely unsubstantiated hearsay as worth a seriously considered response, LubosD...
Facts ten to be things you back up with evidence not blowharding.
Note I did not offer any, beyond the fact of your empty argument, which is both more compelling, and clearly demonstrable.
The fact is, you have a product on a platform that is not BSD, and my subjective although I find reasonable interpretation based on things visible here, rather than a nameless open source project, which could frankly, have been a blog about burning FreeBSD DVDs by the boardwalk, that attracted a pack of arsonists who would confuse IPC with Juggalos. In other words there are a million reasons that your assertion there, just one of many baseless presumptive and irrelevant statements, is worth approximately nothing by weight and volume, other than some scorn. If I were to humor you I would start there, and continue ripping apart all of the nothing you offer while demanding so much. And to take a page from your book, no, I won't. I probably know jack shit about systems. Although you are more than welcome to wildly presume as much as you would like, I'm going to assume, you're angry that you were rejected by some people here, but maybe you should consider before being so butthurt, nobody here came to this page looking for Darling. And you came here to piss down their necks with your project we probably all knew about already. Maybe someone working on security research, and systems, might find this valuable because of the overlap in order to work on cross compilers, and to them, Darling means the fucking princely sum of absolutely useless for the task at hand. I got news for you, if you are trying to fill in the gaps in the open source drops, your project is worth a hell of a lot less for both figuring things out and hacking out crossdev utils, especially if the binary issues matter. And don't go presuming that is intended to answer your damn demand, you haven't put anything out to justify that. I'm merely pointing out that there are many many ways you could be demonstrated absolutely and utterly an ass. Frankly it's not a good look for me either because you already did well enough on your own, I just happened to find this project useful, and think you're a dick.

**Comment by adouble42** [comment]
Hell just on image activators there is a ton useful here, and idk if you are familiar with the disaster of dyld on os x, or the fact that dtrace was a CVE last month not because the dtrace project fucked up - but because that code in particular, was merged in the release version of dyld, there fore, dyld fucked up....now i can't see darling being very useful when it comes to figuring out interactions needed to work on alternative image activators,but running BSD, linux (unlike yourself i am interested in synergy), and xnu variously, I don't often fire up fedora for work. Although, I am perpetually on IRC in a lightdm session exported from a sparc to a ray. Your argument ignores a multitude of concerns that someone developing  a project such as darling should be aware of, and if you aren't, you're a liability and not an asset to your development team, and should be shitcanned. I'm not going to draw a picture more than I have on how image activators work, or maybe the nine million further merits of this project for security research, but I am going to do my damnedest to pull useful work out of it and bring it forward some, an effort which will be a bit harder, because again, I just happened to find this project useful, and think you're a dick.
Then again someone ported osfmk back from high sierra to sierra last week being pissed a macbook pro wouldn't boot, in present form it still doesn't, but, there is some stuff of interest that may apply well here at this entirely unadvertised outside of this bitching session and some emails that never happened, onion hosted git web that got over 240k hits in the last couple weeks, most of which was on a project originally targeting bad, and bare metal cryptography. http://qpbt3kpraplo7ias.onion, the sierra back port is the osfmk, also is dtrace hacks, will probably put image activator right again there...interestingly it does not get through boot on that MBP yet as there, but another more aggressive patchset where I blindly dumped the whole osfmk tree section over this one and made it work, by rewriting a bunch of things in kern and elsewhere to use the new thread structures etc did get it  past the initial hang and into passing early boot, at which point, it hit kdb and page faulted. goal being to preserve the behavior and move the code necessary to boot, missing from the open source drops of 10.12.6 but present in the release binaries of same, that is how i land here. Fuck you buddy, and sorry about my bedside manner. Because I'd prefer to be less polite but, I don't want it to reflect on this project I found useful, just because I think you're a dick.

**Comment by LubosD** [comment]
@adouble42 Have you been taking your meds? :-D

**Comment by RussellHaley** [comment]
From what I understand Jordan Hubbard moved on from iXsystems and iXsystems went a more BSD centric way with TrueOS. Lots of great work and ideas came out of this project. The idea of porting mach system calls is weird though. TrueOS is now a rolling release on head and is using openrc init system. TrueOS is pretty slick right out of the box with zfs, geli, and jails. If your looking for a hardened kernel, then hardenedBSD could be for you (fork of FreeBSD).

Anyway, good luck with Darling. To those that are upset, FreeBSD has excellent Linux emulation. If that's not enough you can run Linux in bhyve quite nicely (to say nothing of vbox in ghostBSD or whatever). 

If someone is looking for a launchd like init system, Mark Heily (not Haley like me) started one called jobd. https://github.com/mheily/jobd.

**Comment by jordanhubbard** [comment]
Wow.  Quite the thread [from hell? 😀] here!

Just for the record, yeah, this project is effectively dead due to lack of time and interest on the part of its developers.  Some of us don't even play with operating systems anymore, focusing more on the application stack side (I'm currently working on DNA nucleotide-specific sensing and mapping devices and software, along with @jceel).  Anyway, it doesn't really matter since this is github and anyone who's interested in this stuff is more than welcome to fork or outright take over our original work.

FWIW, the Linux stuff sounds interesting.  I left the whole "OS wars" battle behind a long time ago as the unproductive and tribalistic exercise that it is, and if @LubosD has managed to make this work in a Linux distribution along with launchd, which I went to considerable effort at Apple to get released as open source, then I think that's absolutely frickin' **terrific** and I wish them the very best of success!   

Life is life, and if our work is finding new life on Linux, then that beats the "death" that NeXTBSD is currently suffering from any day of the week!

**Comment by ghost** [comment]
ok Jordan, ill just ask, turn it over to me and let me see if there is an interest in the community about moving it forward. By the way, hi good to see your doing interesting work, Say hi to Jakub for me.

**Comment by ghost** [comment]
-> LubosD

this is why you stupid bastard

https://wiki.debian.org/Debian_GNU/kFreeBSD

**Comment by jordanhubbard** [comment]
Nah, kFreeBSD has been around for much much longer than NeXTBSD and has much different goals besides.  NeXTBSD was focusing primarily on the kernel side - bringing in Mach IPC and some of the other Darwin goodness at the lowest levels of the system, then bringing launchd, notifyd and other services across once the low-level IPC (and associated kernel-level security mechanisms) were ported.  kFreeBSD is basically just lots of Linux packages running on a stock FreeBSD kernel, which is also great, it's just solving a different problem.
